In [4]:
import pandas as pd

In [11]:
df = pd.read_csv('data/balance-scale.data')
df = df.loc[df['B'].isin(['L','R'])]

df.B = pd.Categorical(df.B)
df['label'] = df.B.cat.codes
df = df.drop(['B'], axis=1)

In [7]:
arr = df.as_matrix()

C:\Users\pogorelov_g\Desktop\work\venv_py36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.

In [9]:
arr.shape

(576, 5)

In [12]:
df

     1  1.1  1.2  1.3  label
0    1    1    1    2      1
1    1    1    1    3      1
2    1    1    1    4      1
3    1    1    1    5      1
4    1    1    2    1      1
5    1    1    2    2      1
6    1    1    2    3      1
7    1    1    2    4      1
8    1    1    2    5      1
9    1    1    3    1      1
10   1    1    3    2      1
11   1    1    3    3      1
12   1    1    3    4      1
13   1    1    3    5      1
14   1    1    4    1      1
15   1    1    4    2      1
16   1    1    4    3      1
17   1    1    4    4      1
18   1    1    4    5      1
19   1    1    5    1      1
20   1    1    5    2      1
21   1    1    5    3      1
22   1    1    5    4      1
23   1    1    5    5      1
24   1    2    1    1      0
26   1    2    1    3      1
27   1    2    1    4      1
28   1    2    1    5      1
30   1    2    2    2      1
31   1    2    2    3      1
..  ..  ...  ...  ...    ...
591  5    4    4    3      0
592  5    4    4    4      0
594  5    4    5    1      0
595  5    4    5    2      0
596  5    4    5    3      0
598  5    4    5    5      1
599  5    5    1    1      0
600  5    5    1    2      0
601  5    5    1    3      0
602  5    5    1    4      0
603  5    5    1    5      0
604  5    5    2    1      0
605  5    5    2    2      0
606  5    5    2    3      0
607  5    5    2    4      0
608  5    5    2    5      0
609  5    5    3    1      0
610  5    5    3    2      0
611  5    5    3    3      0
612  5    5    3    4      0
613  5    5    3    5      0
614  5    5    4    1      0
615  5    5    4    2      0
616  5    5    4    3      0
617  5    5    4    4      0
618  5    5    4    5      0
619  5    5    5    1      0
620  5    5    5    2      0
621  5    5    5    3      0
622  5    5    5    4      0

[576 rows x 5 columns]